id: IF6EAA761
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-08T00:56:07+00:00'
last_modified: '2022-06-16T07:44:34.029595+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2KG5015
  title: བསྟན་འགྱུར། ༼སྣར་ཐང་།༽
  author: ''
  base:
    '3844':
      image_group_id: I2KG212285
      title: ''
      total_pages: ''
      order: 1
      base_file: 3844.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
